# Generated by Django 2.2.12 on 2020-05-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=50)),
                ('ownedby', models.CharField(max_length=50)),
                ('operator', models.CharField(max_length=100)),
                ('users', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
                ('detpurpose', models.CharField(max_length=50)),
                ('orbit_class', models.CharField(max_length=50)),
                ('orbit_type', models.CharField(max_length=50)),
                ('GEO_longitude', models.IntegerField()),
                ('perigee', models.IntegerField()),
                ('apogee', models.IntegerField()),
                ('eccentricity', models.CharField(max_length=50)),
                ('inclination', models.IntegerField()),
                ('period', models.IntegerField()),
                ('launch_mass', models.IntegerField()),
                ('dry_mass', models.IntegerField()),
                ('power', models.IntegerField()),
                ('launch_date', models.CharField(max_length=20)),
                ('Expected_lifetime', models.IntegerField()),
                ('contractor', models.CharField(max_length=50)),
                ('country_of_contractor', models.CharField(max_length=50)),
                ('launch_site', models.CharField(max_length=50)),
                ('launch_vehicle', models.CharField(max_length=50)),
                ('COSPAR_number', models.CharField(max_length=50)),
                ('NORAD_number', models.IntegerField()),
                ('comments', models.CharField(max_length=50)),
                ('orbital_data_source', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
