# Generated by Django 2.2.12 on 2021-06-24 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news',
        ),
    ]
