# Generated by Django 2.2.12 on 2021-06-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('up', '0002_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Expected_lifetime',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='GEO_longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='NORAD_number',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='apogee',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='dry_mass',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='inclination',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='launch_mass',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='perigee',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='period',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='power',
            field=models.FloatField(),
        ),
    ]
